import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MCW OmWork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar />
        <div className={styles.body}>
          <div className={styles.header}>
            <div className={styles.greeting}>
              <h2>Hello, Aldous!</h2>
              <p>Today is Monday, Febuary 5th</p>
            </div>
            <div className={styles.progress}>Progress</div>
          </div>
          <h2 className={styles.current_week}>This Week's Assignments:</h2>
          <div className={styles.assignment_container}>
            <div className={styles.assignment}>Reading</div>
            <div className={styles.assignment}>Breathing</div>
            <div className={styles.assignment}>Stretching</div>
          </div>
          <footer className={styles.footer}>Powered By dbwebdev</footer>
        </div>
      </main>
    </div>
  );
}
